// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnneeetblzgsjpcuxqvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJubmVlZXRibHpnc2pwY3V4cXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2Mzk4OTgsImV4cCI6MjA2NDIxNTg5OH0.scIBJWuByHI3SWYFUOacVRNmZtqd2cYvklqZIfCWS0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = 
createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

